version: '3.7'
services:
    postgres:
        image: postgres:12
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes:
          - ./db-backups:/var/lib/postgresql
          - ./db-data:/var/lib/postgresql/data
          - ./sql/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
          - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
          - ./sql/grant-permissions.sql:/docker-entrypoint-initdb.d/grant-permissions.sql